### PR TITLE
Fix modules directories

### PR DESCRIPTION
**Pull request by ramiel**
I'm sorry, I have no time to check test.

### CODE REVIEW

**Comment by ramiel** [comment]
I mean, this is not a fix, just what I think is almost missing

**Comment by chmanie** [comment]
OK, just to be clear:

You have a directory containing files like this:
```
..
.
foo.js
bar.js
baz.js
```

and you want to be able to just do `import foo from 'foo'` which will import the `foo.js` files default export.

I don't know whether I think this is a good idea but who am I to judge ¯\_(ツ)_/¯.

I considered `moduleDirectories` to be a directory where you put modules which are again inside folders (just like node_modules or bower_components).

If jest supports that I'll add it here.

**Comment by ramiel** [comment]
To be clearer, this is the use case.     
`moduleDirectories` is a set of folders and by default is `["node_modules"]`. You can add your own and in that case you must specify `node_modules`. The order matters.    
You have this.

```
-src
 | - a.js
 | - b.js 
 | sub
    | - c.js
- node_modules
 | fetch
```

in your jest config you specify

```
"moduleDirectories": ["node_modules", "src"]
```

and in your test you can write

```
const fetch = require('fetch');
const a = require('a');
const c = require('sub/c');
```

**Comment by chmanie** [comment]
Yep. Got it. Thanks!

**Comment by chmanie** [comment]
This should be fixed in v2.0.0. Hope it'll work for you!

**Comment by ramiel** [comment]
Great!

**Pull request closed without merging**
